development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plew-dev1_development
  pool: 5
  username: root
  password: ananas
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plew-dev1_test
  pool: 5
  username: root
  password: ananas
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: plew-dev1_development
  pool: 5
  username: root
  password: ananas
  host: localhost
